### ISSUE TITLE
[Question] How do we handle cache invalidation?

### ISSUE THREAD

**Issue by rognales** [rennokki/laravel-eloquent-query-cache#15]
Does the package automatically invalidate the cache whenever new Eloquent records is created/updated/deleted?

**Comment by rennokki** [comment]
@rognales 

It does not because in some certain cases, you may cache some queries for a small amount of time (like 5 minutes or so) and not trigger a cache invalidation, making the following query to trigger another query instead of taking it from the cache.

What you might want to do, is to implement [observers](https://laravel.com/docs/7.x/eloquent#observers) on your models in which you can trigger the cache invalidation.

**Comment by shinsenter** [comment]
Please check the PR #16

**Comment by rennokki** [comment]
Also check #19 

Tag: https://github.com/rennokki/laravel-eloquent-query-cache/releases/tag/1.4.0
